Discord:
  Token: ~ # Required: string
  LogChannelIds: ~ # Optional: number[]
  Modules:
    ElasticVoiceChannels:
      ExcludedChannelIds: ~ # Optional: number[]
      MaxGroupChannelCount: ~ # Optional: number
Logging:
  LogLevel:
    Default: "Information"
    # Optional: Log levels for other namespace prefixes.