Discord:
  Token: ~ # Required: string
  Modules:
    ElasticVoiceChannels:
      ExcludedChannelIds: ~ # Optional: ulong[]
Logging:
  LogLevel:
    Default: "Debug"
    System: "Information"
    Microsoft: "Information"