Discord:
  Token: ~ # Required: string
  Modules:
    ElasticVoiceChannels:
      ExcludedChannelIds: ~ # Optional: number[]
      MaxGroupChannelCount: ~ # Optional: number
Logging:
  LogLevel:
    Default: "Debug"
    System: "Information"
    Microsoft: "Information"